name: ShellCheck

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          format: gcc
          severity: warning
        env:
          SHELLCHECK_OPTS: -e SC1091 -e SC1090